(function() {var implementors = {};
implementors["mpl_auction"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.57.0/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"mpl_auction/errors/enum.AuctionError.html\" title=\"enum mpl_auction::errors::AuctionError\">AuctionError</a>","synthetic":false,"types":["mpl_auction::errors::AuctionError"]}];
implementors["mpl_auction_house"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.57.0/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"mpl_auction_house/enum.ErrorCode.html\" title=\"enum mpl_auction_house::ErrorCode\">ErrorCode</a>","synthetic":false,"types":["mpl_auction_house::ErrorCode"]}];
implementors["mpl_gumdrop"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.57.0/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"mpl_gumdrop/enum.ErrorCode.html\" title=\"enum mpl_gumdrop::ErrorCode\">ErrorCode</a>","synthetic":false,"types":["mpl_gumdrop::ErrorCode"]}];
implementors["mpl_metaplex"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.57.0/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"mpl_metaplex/error/enum.MetaplexError.html\" title=\"enum mpl_metaplex::error::MetaplexError\">MetaplexError</a>","synthetic":false,"types":["mpl_metaplex::error::MetaplexError"]}];
implementors["mpl_nft_packs"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.57.0/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"mpl_nft_packs/error/enum.NFTPacksError.html\" title=\"enum mpl_nft_packs::error::NFTPacksError\">NFTPacksError</a>","synthetic":false,"types":["mpl_nft_packs::error::NFTPacksError"]}];
implementors["mpl_token_entangler"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.57.0/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"mpl_token_entangler/enum.ErrorCode.html\" title=\"enum mpl_token_entangler::ErrorCode\">ErrorCode</a>","synthetic":false,"types":["mpl_token_entangler::ErrorCode"]}];
implementors["mpl_token_metadata"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.57.0/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"mpl_token_metadata/error/enum.MetadataError.html\" title=\"enum mpl_token_metadata::error::MetadataError\">MetadataError</a>","synthetic":false,"types":["mpl_token_metadata::error::MetadataError"]}];
implementors["mpl_token_vault"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.57.0/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"mpl_token_vault/error/enum.VaultError.html\" title=\"enum mpl_token_vault::error::VaultError\">VaultError</a>","synthetic":false,"types":["mpl_token_vault::error::VaultError"]}];
implementors["nft_candy_machine"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.57.0/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"nft_candy_machine/enum.ErrorCode.html\" title=\"enum nft_candy_machine::ErrorCode\">ErrorCode</a>","synthetic":false,"types":["nft_candy_machine::ErrorCode"]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()