(function() {var implementors = {};
implementors["mpl_auction"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.57.0/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"mpl_auction/errors/enum.AuctionError.html\" title=\"enum mpl_auction::errors::AuctionError\">AuctionError</a>&gt; for ProgramError","synthetic":false,"types":["solana_program::program_error::ProgramError"]}];
implementors["mpl_auction_house"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.57.0/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"mpl_auction_house/enum.ErrorCode.html\" title=\"enum mpl_auction_house::ErrorCode\">ErrorCode</a>&gt; for ProgramError","synthetic":false,"types":["solana_program::program_error::ProgramError"]}];
implementors["mpl_gumdrop"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.57.0/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"mpl_gumdrop/enum.ErrorCode.html\" title=\"enum mpl_gumdrop::ErrorCode\">ErrorCode</a>&gt; for ProgramError","synthetic":false,"types":["solana_program::program_error::ProgramError"]}];
implementors["mpl_metaplex"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.57.0/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"mpl_metaplex/error/enum.MetaplexError.html\" title=\"enum mpl_metaplex::error::MetaplexError\">MetaplexError</a>&gt; for ProgramError","synthetic":false,"types":["solana_program::program_error::ProgramError"]}];
implementors["mpl_nft_packs"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.57.0/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"mpl_nft_packs/error/enum.NFTPacksError.html\" title=\"enum mpl_nft_packs::error::NFTPacksError\">NFTPacksError</a>&gt; for ProgramError","synthetic":false,"types":["solana_program::program_error::ProgramError"]}];
implementors["mpl_token_entangler"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.57.0/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"mpl_token_entangler/enum.ErrorCode.html\" title=\"enum mpl_token_entangler::ErrorCode\">ErrorCode</a>&gt; for ProgramError","synthetic":false,"types":["solana_program::program_error::ProgramError"]}];
implementors["mpl_token_metadata"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.57.0/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"mpl_token_metadata/error/enum.MetadataError.html\" title=\"enum mpl_token_metadata::error::MetadataError\">MetadataError</a>&gt; for ProgramError","synthetic":false,"types":["solana_program::program_error::ProgramError"]}];
implementors["mpl_token_vault"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.57.0/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"mpl_token_vault/error/enum.VaultError.html\" title=\"enum mpl_token_vault::error::VaultError\">VaultError</a>&gt; for ProgramError","synthetic":false,"types":["solana_program::program_error::ProgramError"]}];
implementors["nft_candy_machine"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.57.0/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"nft_candy_machine/enum.ErrorCode.html\" title=\"enum nft_candy_machine::ErrorCode\">ErrorCode</a>&gt; for ProgramError","synthetic":false,"types":["solana_program::program_error::ProgramError"]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()